# Generated by Django 3.0.7 on 2020-12-04 21:47

from django.db import migrations, models
import markdownx.models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201129_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', markdownx.models.MarkdownxField()),
                ('phone', phone_field.models.PhoneField(blank=True, help_text="Company's Phone number", max_length=31)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
